language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - ./bin/build

script:
  - ./bin/test
  - php ./vendor/bin/coveralls -v -n -x ./tmp/clover.xml
